### ISSUE TITLE
How to read the Input passed from workflow in Code

### ISSUE THREAD

**Issue by jegadjame** [erikbrgr/supersimpleconductor#14]
Hi, 
I need to read the input data (in below code, JobType :3) in code . Please help in reading the data in onExecute in the code.
{
    "name": "TestWorkFlow13",
    "version": 2,
    "correlationId": "meaningful_unique_correlationId",
    "input": 
    {
         "JobType": "3"
    }
}

Thanks,
Jegadeesh

**Comment by erikbrgr** [comment]
Hi @jegadjame,

The `WorkflowTask` model has a property `InputData` which contains that information. So it's a property of your class and can be accessed using `this.InputData`. 

Best,
Erik

**Comment by jegadjame** [comment]
Thank You Erik... I am able to get data now by accessing using this.InputData
