### ISSUE TITLE
SuperSimpleConductor Issues in .net 6.0

### ISSUE THREAD

**Issue by jegadjame** [erikbrgr/supersimpleconductor#15]
Hi,
I am using nuget package of SuperSimpleConductor.ConductorClient (Version0.3.1) and SuperSimpleConductor.ConductorWorker (Version0.3.1) which are the latest versions. It is working fine when I use Target Framework as **.NET core 3.1**).

Now, When I upgrade the  .NET framework to **.NET 6.0**, I am getting refit error. Looks like Refit is not updated. 

We will be happy to get next version of SuperSimpleConductor Nuget which works with the latest .Net version early

![image](https://user-images.githubusercontent.com/5119603/195507072-a727abe6-761c-4c9e-b3f3-4ffffd003fbb.png)

Thanks,
Jegadeesh

**Comment by erikbrgr** [comment]
Hi,

This is very unlikely to be a Refit issue. .Net Core 3.1 libraries are 100% compatible with .Net 6.0. 

If you read the error message carefully, you see you're getting a 403 error connecting to the Conductor API. This is an authentication or routing issue which is unrelated to Refit or SSC.

**Comment by jegadjame** [comment]
Hi,
I am using the Latest version of conductor 3.9.2. Not sure why I am getting issue only when i change the version to .net 6.0.. I will try to debug..

Thanks,
Jegadeesh

**Comment by jegadjame** [comment]
It is working now.. It was Proxy Issue in my system.. 

Thanks,
Jegadeesh

**Comment by erikbrgr** [comment]
Hi,

Good news! Glad it's working for you now.
