### ISSUE TITLE
 getting the assembly name for workflow

### ISSUE THREAD

**Issue by jegadjame** [erikbrgr/supersimpleconductor#9]
Hi,
I am new to implement netflix conductor.

Can you please help me in getting the assembly name for below line.

services.AddWorkflowTasks("assembly containing your worker tasks");

If i Give 'SuperSimpleConductor.ConductorWorker', I am getting error 'Response status code does not indicate success: 404 (Not Found)' in ConductorApi.GetQueue()
I have started swagger(http://localhost:8080/) and conductor UI (http://localhost:5000/)  on

Thanks in Advance

**Comment by erikbrgr** [comment]
Hi,

This is the name of the assembly you defined your WorkerTasks in (using the supplied base class). The name is easy to find, just build your project and look in the output folder. Generally, the name matches the name of the project, with “.dll” added.

Hope this helps.

On 22 Mar 2022, at 11:42, jegadjame ***@***.***> wrote:

﻿

Hi,
I am new to implement netflix conductor.

Can you please help me in getting the assembly name for below line.

services.AddWorkflowTasks("");

I have started swagger(http://localhost:8080/) and conductor UI (http://localhost:5000/) on

Thanks in Advance

**Comment by erikbrgr** [comment]
Hi @jegadjame ,

The TestWorker project should contain everything you need. 
- It contains the class `SimpleSampleWorkerTask`, which defines a task.
- If you build the TestWorker project, it will create a `TestWorker.dll` in the `bin/Debug/netcoreapp3.1` folder. This dll will contain the `SimpleSampleWorkerTask`, so you'll need to add that dll to the AddWorkflowTasks call, as can be seen in `Program.cs` at line 23.

SupportedTaskTypes is filled by the RegisterWorkflowTasks call on line 12 of `Program.cs`. This call will register all WorkflowTasks that were added using `AddWorkflowTask` (as it states in the documentation comments of RegisterWorkflowTasks).

TaskDomain is not mandatory. We use it to seperate two sets of Workers that are responsible for seperate sets of tasks in Conductor.

Hope this helps. Please let me know if you have more questions.

**Comment by jegadjame** [comment]
Hi @erikbrgr ,
Thank you for your time

I have added services.AddWorkflowTasks("TestWorker"); in program.cs of Testworker  project

But still , I am getting workflowTaskTypes  count as 0 in Dependencyinjection.cs in the below line
var workflowTaskTypes = workflowTaskAssembly.GetExportedTypes().Where(t => typeof(IWorkflowTask).IsAssignableFrom(t) && !t.IsAbstract);

Do i need to create anything in netflix conductor before trying to execute the code.
![image](https://user-images.githubusercontent.com/5119603/159692419-9974513c-dda0-4b4b-95a3-b931072529f3.png)

**Comment by erikbrgr** [comment]
Odd. If I run the debugger, I get this:
![image](https://user-images.githubusercontent.com/19207888/159707647-06f5959a-c7c0-4403-8b24-f8e8812e6ee1.png)

Can you copy/paste the full code of your Program.cs? Did you make any changes to the TestWorker project?

**Comment by jegadjame** [comment]
Hi @erikbrgr ,

Thank you for your time

Below is the code. I didn't modify anything in the code

using Microsoft.Extensions.Hosting;
using System;
using SuperSimpleConductor.ConductorWorker;
using SuperSimpleConductor.ConductorClient;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Refit;

namespace TestWorker
{
   public class Program
   {
      public static void Main(string[] args)
      {
         CreateHostBuilder(args).Build()
                                .RegisterWorkflowTasks()
                                .Run();
      }

      public static IHostBuilder CreateHostBuilder(string[] args) =>
                Host.CreateDefaultBuilder(args)
                    .ConfigureServices((hostContext, services) =>
                    {
                       services.AddConductorWorker(hostContext.Configuration, new Uri("http://localhost:8080/"));

                       //services.AddTransient<IConductorApiExceptionHandler, ConductorApiExceptionHandler>();

                       services.AddWorkflowTasks("TestWorker");
                    });
   }

   public class ConductorApiExceptionHandler : IConductorApiExceptionHandler
   {
      public ILogger<ConductorApiExceptionHandler> Logger { get; }

      public ConductorApiExceptionHandler(ILogger<ConductorApiExceptionHandler> logger)
      {
         Logger = logger;
      }

      public ConductorApi HandleException(Exception exception, ConductorApi conductorApi)
      {
         Logger.LogError("Error calling Conductor api");

         try
         {
            Logger.LogInformation("Attempting to recover..");

            // Simulate api discovery
            var conductorApiUrl = "http://localhost:8080";

            conductorApi = RestService.For<ConductorApi>(conductorApiUrl);

            Logger.LogInformation("New Conductor api address found: {conductorApi}", conductorApiUrl);

            return conductorApi;
         }
         catch (Exception ex)
         {
            Logger.LogError(ex, "Unable to recover");
            return null;
         }
      }
   }
}

**Comment by erikbrgr** [comment]
Hi @jegadjame,

I am so sorry. I am actually 1 version ahead of you because of a pending PR. In your version, there is no sample Task implementation. So  of course it will not be found :)

You are missing the following file: https://github.com/erikbrgr/supersimpleconductor/blob/608f0a25db611ff9f0e475edacd6e461e942305b/TestWorker/SimpleSampleWorkerTask.cs

Please create this file in your TestWorker project and let me know if it works, then.

**Comment by jegadjame** [comment]
Hi @erikbrgr ,

Thanks a lot for your time. I am able to proceed.

In WorkflowTaskCoordinator.cs, In PollConductorQueue method, It is filtered for "SupportedTaskTypes" only. Will i be able to add the tasks from the netflix conductor. I am able to read the taskname from Queue.

If i skip the SupportedTaskTypes filter, I will not get the taskType.

Can you please help me in adding the Tasks created from Netflix conductor

![image](https://user-images.githubusercontent.com/5119603/159720458-5f6a1de8-64e4-4626-aeaf-25e0cb86473c.png)

![image](https://user-images.githubusercontent.com/5119603/159718355-2c902e6b-249c-4c28-ab7c-65f5c10eddbe.png)

**Comment by erikbrgr** [comment]
That is good news, @jegadjame.

To connect the Conductor task to the .NET class, it is required that the name of the tasks are identical. This is the convention.

So, in the example, you have the `SimpleSampleWorkerTask`. In Conductor, you register the task under the same name using the task definition:
```json
{
   "name": "SimpleSampleWorkerTask",
   ... (the rest of your definition)
}
```

Or, vice versa, you have your Conductor task `Send_Email_Discount_Next_Order`, so you need to create a class:
```cs
public class Send_Email_Discount_Next_Order : WorkflowTask<Send_Email_Discount_Next_Order>
{
   ... (implementation)
}
```

The `services.AddWorkflowTasks` call as before will then make sure the `Send_Email_Discount_Next_Order` task is registered in SupportedTypes.

**Comment by erikbrgr** [comment]
No trouble at all, @jegadjame, happy to help. 

Can you paste the content of the taskresult variable when calling UpdateTask, as well as the full requestMessage? It’s probably a small thing. 

I’ll then look into it in the morning :)

**Comment by erikbrgr** [comment]
Nothing obviously wrong there. What I'd suggest is to execute the updatetask using wither Postman or the Swagger API and see what's up. There's a PR coming (hopefully today) that contains a HttpLogger so you can see the payloads being sent to Conductor. 

It will also fix an issue with case sensitive payloads  (#7) which might be the issue here. Are you running on Windows or Mac/Linux? Windows is case insensitive, whereas everyone else is case sensitive. The PR will address that issue.

I'm also working on a "Getting Started" article using SuperSimpleConductor and the information in this article: https://betterprogramming.pub/running-netflix-conductor-3-in-docker-using-elasticsearch-7-and-postgresql-b415988dd74a which might be useful for you. But that's a little while yet.

**Comment by erikbrgr** [comment]
Hi @jegadjame ,

I've just released v0.3.1, which includes the abovementioned fixes and helper class. Please update to the latest release and see if this resolves your issue. If not, please open a new issue. You can reference this issue, obviously.

I'll close this now and wait for your feedback.

**Comment by jegadjame** [comment]
Hi @erikbrgr , 
Thanks a lot for your patience and time

**Comment by erikbrgr** [comment]
Did you actually implement any WorkflowTasks?

I’ll dig up a quick example when I am at my work computer again, tomorrow.

On 22 Mar 2022, at 15:25, jegadjame ***@***.***> wrote:

﻿

Thank you .. it helped

I have cloned the proect and followed the steps from readme file.
services.AddConductorWorker(hostContext.Configuration, new Uri("http://localhost:8080/api"));
services.AddWorkflowTasks("SuperSimpleConductor.ConductorWorker");
When I try to add AddWorkflowTasks, I always see workflowTaskTypes.Count() as 0. Is there any prerequiste i need to follow this to work.

Thanks in Advance

**Comment by jegadjame** [comment]
Hi,
I have implemented sample workflow and it looks fine

Thanks,
Jegadeesh

**Comment by erikbrgr** [comment]
Awesome, well done 😄
